export interface Tool {
  id: string;
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  category: 'image' | 'pdf';
  subcategory: string;
  icon: string;
  features: string[];
  keywords: string[];
  popular: boolean;
  new?: boolean;
  trending?: boolean;
}

export const IMAGE_TOOLS: Tool[] = [
  {
    id: 'img-compress',
    name: 'Smart Image Compressor',
    slug: 'compress-image',
    description: 'Compress images to any size with smart optimization. Reduce image file size while maintaining quality. Supports JPG, PNG, WebP, and more.',
    shortDescription: 'Compress images to any KB/MB with smart optimization',
    category: 'image',
    subcategory: 'compression',
    icon: 'Minimize2',
    features: ['Compress to custom KB/MB', 'Quality slider', 'Batch processing', 'Live preview', 'ZIP download', 'Preserve transparency'],
    keywords: ['compress image', 'reduce image size', 'image compressor online', 'compress jpg', 'compress png'],
    popular: true,
    trending: true,
  },
  {
    id: 'img-resize',
    name: 'Smart Image Resizer',
    slug: 'resize-image',
    description: 'Resize images by pixels, percentage, inches, or cm. Use presets for social media, passports, and documents. Batch resize with advanced controls.',
    shortDescription: 'Resize images by px, %, inches, or cm with presets',
    category: 'image',
    subcategory: 'resize',
    icon: 'Maximize2',
    features: ['Resize by pixels/percentage/inches/cm', 'Aspect ratio lock', 'Social media presets', 'DPI control', 'Batch resize', 'Smart crop'],
    keywords: ['resize image', 'image resizer online', 'resize photo', 'change image dimensions'],
    popular: true,
    trending: true,
  },
  {
    id: 'img-convert',
    name: 'Smart Image Converter',
    slug: 'convert-image',
    description: 'Convert images between JPG, PNG, WebP, AVIF, BMP, TIFF, ICO, and more. Batch conversion with quality settings and transparency support.',
    shortDescription: 'Convert between JPG, PNG, WebP, AVIF & more',
    category: 'image',
    subcategory: 'conversion',
    icon: 'RefreshCw',
    features: ['All major formats', 'Batch conversion', 'Quality control', 'Transparency support', 'Metadata options', 'ZIP download'],
    keywords: ['convert image', 'jpg to png', 'png to jpg', 'image converter online', 'webp converter'],
    popular: true,
  },
  {
    id: 'img-crop',
    name: 'Advanced Image Crop',
    slug: 'crop-image',
    description: 'Crop images with precision. Use free crop, aspect ratio lock, or preset dimensions for social media, passports, and documents.',
    shortDescription: 'Crop images with precision controls and presets',
    category: 'image',
    subcategory: 'editing',
    icon: 'Crop',
    features: ['Free crop', 'Aspect ratio presets', 'Pixel-perfect control', 'Live preview', 'Batch crop'],
    keywords: ['crop image', 'image cropper', 'crop photo online'],
    popular: true,
  },
  {
    id: 'img-rotate',
    name: 'Rotate & Flip Image',
    slug: 'rotate-flip-image',
    description: 'Rotate images by any angle or flip horizontally/vertically. Fix image orientation issues instantly.',
    shortDescription: 'Rotate by any angle or flip images',
    category: 'image',
    subcategory: 'editing',
    icon: 'RotateCw',
    features: ['Rotate 90/180/270', 'Custom angle', 'Flip horizontal/vertical', 'Batch processing', 'EXIF fix'],
    keywords: ['rotate image', 'flip image', 'image rotation online'],
    popular: false,
  },
  {
    id: 'img-watermark',
    name: 'Image Watermark Tool',
    slug: 'add-watermark',
    description: 'Add text or image watermarks to photos. Customize position, opacity, size, and apply to multiple images at once.',
    shortDescription: 'Add text or image watermarks to photos',
    category: 'image',
    subcategory: 'editing',
    icon: 'Stamp',
    features: ['Text watermark', 'Image watermark', 'Custom position', 'Opacity control', 'Batch watermark', 'Tiled pattern'],
    keywords: ['add watermark', 'watermark image', 'bulk watermark'],
    popular: true,
  },
  {
    id: 'img-dpi',
    name: 'Image DPI Converter',
    slug: 'change-image-dpi',
    description: 'Change image DPI/PPI for printing or digital use. Convert between 72, 96, 150, 300, 600 DPI and custom values.',
    shortDescription: 'Change image DPI for print or digital',
    category: 'image',
    subcategory: 'editing',
    icon: 'Target',
    features: ['Custom DPI', 'Preset values', 'Print optimization', 'Batch processing', 'Resolution info'],
    keywords: ['change dpi', 'image dpi converter', '300 dpi converter'],
    popular: true,
  },
  {
    id: 'img-passport',
    name: 'Passport Photo Maker',
    slug: 'passport-photo-maker',
    description: 'Create passport-size photos for any country. Supports US, UK, India, Schengen, and 50+ country formats with background options.',
    shortDescription: 'Create passport photos for any country',
    category: 'image',
    subcategory: 'specialized',
    icon: 'User',
    features: ['50+ country formats', 'Auto background', 'Face detection guide', 'Print layout', 'Custom dimensions', 'DPI optimization'],
    keywords: ['passport photo maker', 'passport size photo', 'visa photo maker'],
    popular: true,
    trending: true,
  },
  {
    id: 'img-metadata',
    name: 'Image Metadata Viewer',
    slug: 'image-metadata-viewer',
    description: 'View complete EXIF and metadata information of any image including camera, GPS, date, and technical details.',
    shortDescription: 'View EXIF, GPS, camera info from images',
    category: 'image',
    subcategory: 'utility',
    icon: 'Info',
    features: ['Full EXIF data', 'GPS location', 'Camera info', 'Color profile', 'File details', 'Export metadata'],
    keywords: ['image metadata', 'exif viewer', 'photo metadata'],
    popular: false,
  },
  {
    id: 'img-metadata-remove',
    name: 'Image Metadata Remover',
    slug: 'remove-image-metadata',
    description: 'Strip all metadata and EXIF data from images for privacy. Remove GPS, camera info, and personal data.',
    shortDescription: 'Remove EXIF and metadata for privacy',
    category: 'image',
    subcategory: 'utility',
    icon: 'ShieldOff',
    features: ['Remove all EXIF', 'Remove GPS', 'Batch processing', 'Preserve quality', 'Privacy protection'],
    keywords: ['remove metadata', 'strip exif', 'remove image data'],
    popular: false,
  },
  {
    id: 'img-color-picker',
    name: 'Color Picker from Image',
    slug: 'color-picker',
    description: 'Pick colors from any image. Get HEX, RGB, HSL values. Extract color palettes and create harmonious color schemes.',
    shortDescription: 'Extract colors and palettes from images',
    category: 'image',
    subcategory: 'utility',
    icon: 'Pipette',
    features: ['HEX/RGB/HSL values', 'Color palette extraction', 'Click to pick', 'Copy codes', 'Palette export'],
    keywords: ['color picker', 'image color picker', 'extract colors from image'],
    popular: true,
  },
  {
    id: 'img-qr',
    name: 'QR Code Generator',
    slug: 'qr-code-generator',
    description: 'Generate high-quality QR codes for URLs, text, WiFi, vCards, and more. Customize colors, add logos, and download in multiple formats.',
    shortDescription: 'Generate customizable QR codes',
    category: 'image',
    subcategory: 'generator',
    icon: 'QrCode',
    features: ['URL/Text/WiFi/vCard', 'Custom colors', 'Logo embedding', 'Multiple sizes', 'SVG/PNG export', 'Batch generate'],
    keywords: ['qr code generator', 'create qr code', 'qr maker online'],
    popular: true,
    trending: true,
  },
  {
    id: 'img-bulk-compress',
    name: 'Bulk Image Compressor',
    slug: 'bulk-compress-images',
    description: 'Compress hundreds of images at once with smart optimization. Maintains quality while dramatically reducing file sizes.',
    shortDescription: 'Compress hundreds of images at once',
    category: 'image',
    subcategory: 'compression',
    icon: 'Layers',
    features: ['Unlimited batch', 'Smart optimization', 'ZIP download', 'Progress tracking', 'Custom settings per file'],
    keywords: ['bulk compress images', 'batch image compression', 'compress multiple images'],
    popular: true,
  },
  {
    id: 'img-bulk-resize',
    name: 'Bulk Image Resizer',
    slug: 'bulk-resize-images',
    description: 'Resize multiple images at once with consistent dimensions. Perfect for e-commerce, social media, and web preparation.',
    shortDescription: 'Resize multiple images simultaneously',
    category: 'image',
    subcategory: 'resize',
    icon: 'LayoutGrid',
    features: ['Batch resize', 'Consistent dimensions', 'Percentage scaling', 'ZIP download', 'Quality control'],
    keywords: ['bulk resize images', 'batch image resizer', 'resize multiple images'],
    popular: true,
  },
  {
    id: 'img-to-pdf',
    name: 'Images to PDF',
    slug: 'images-to-pdf',
    description: 'Convert multiple images to a single PDF document. Control page size, orientation, margins, and image quality.',
    shortDescription: 'Convert multiple images to a PDF',
    category: 'image',
    subcategory: 'conversion',
    icon: 'FileText',
    features: ['Multiple images to PDF', 'Page size options', 'Orientation control', 'Margin settings', 'Quality control', 'Reorder pages'],
    keywords: ['images to pdf', 'jpg to pdf', 'png to pdf', 'photo to pdf'],
    popular: true,
  },
  {
    id: 'img-background',
    name: 'Image Background Color',
    slug: 'change-background-color',
    description: 'Change or add background color to transparent images. Perfect for product photos, logos, and transparent PNGs.',
    shortDescription: 'Change background color of images',
    category: 'image',
    subcategory: 'editing',
    icon: 'Palette',
    features: ['Custom colors', 'Transparent to colored', 'White background', 'Batch processing', 'Color picker'],
    keywords: ['change background color', 'add background to image', 'image background'],
    popular: false,
  },
  {
    id: 'img-bw',
    name: 'Black & White Converter',
    slug: 'black-and-white',
    description: 'Convert color images to black and white or grayscale. Adjust contrast and brightness for perfect monochrome results.',
    shortDescription: 'Convert images to black & white',
    category: 'image',
    subcategory: 'filters',
    icon: 'Contrast',
    features: ['Grayscale conversion', 'Contrast control', 'Brightness adjustment', 'Batch processing', 'Live preview'],
    keywords: ['black and white image', 'grayscale converter', 'monochrome photo'],
    popular: false,
  },
  {
    id: 'img-blur',
    name: 'Image Blur Tool',
    slug: 'blur-image',
    description: 'Apply gaussian blur, motion blur, or selective blur to images. Great for backgrounds, privacy, and artistic effects.',
    shortDescription: 'Apply blur effects to images',
    category: 'image',
    subcategory: 'filters',
    icon: 'Droplets',
    features: ['Gaussian blur', 'Blur intensity', 'Selective blur', 'Live preview', 'Batch processing'],
    keywords: ['blur image', 'image blur tool', 'gaussian blur online'],
    popular: false,
  },
  {
    id: 'img-sharpen',
    name: 'Image Sharpen Tool',
    slug: 'sharpen-image',
    description: 'Sharpen blurry or soft images with adjustable intensity. Enhance details and clarity without artifacts.',
    shortDescription: 'Sharpen and enhance image clarity',
    category: 'image',
    subcategory: 'filters',
    icon: 'Zap',
    features: ['Adjustable sharpening', 'Unsharp mask', 'Detail enhancement', 'Live preview', 'Batch processing'],
    keywords: ['sharpen image', 'enhance image', 'fix blurry image'],
    popular: false,
  },
  {
    id: 'img-favicon',
    name: 'Favicon Generator',
    slug: 'favicon-generator',
    description: 'Generate favicons in all required sizes from any image. Creates ICO, PNG, and Apple Touch icons ready for web use.',
    shortDescription: 'Generate all favicon sizes from any image',
    category: 'image',
    subcategory: 'generator',
    icon: 'Globe',
    features: ['All sizes generated', 'ICO format', 'Apple Touch icons', 'Android icons', 'HTML code snippet', 'ZIP download'],
    keywords: ['favicon generator', 'create favicon', 'ico generator'],
    popular: true,
  },
];

export const PDF_TOOLS: Tool[] = [
  {
    id: 'pdf-compress',
    name: 'Smart PDF Compressor',
    slug: 'compress-pdf',
    description: 'Compress PDF files to any size with intelligent optimization. Reduce file size while maintaining readability. Multiple compression modes available.',
    shortDescription: 'Compress PDFs to any size with smart optimization',
    category: 'pdf',
    subcategory: 'compression',
    icon: 'FileDown',
    features: ['Compress to custom KB/MB', 'Quality modes', 'Batch compression', 'Preserve quality', 'ZIP download', 'Ultra-fast'],
    keywords: ['compress pdf', 'reduce pdf size', 'pdf compressor online', 'shrink pdf'],
    popular: true,
    trending: true,
  },
  {
    id: 'pdf-merge',
    name: 'Merge PDF Files',
    slug: 'merge-pdf',
    description: 'Combine multiple PDF files into one document. Drag and drop to reorder pages. Fast, secure, and free.',
    shortDescription: 'Combine multiple PDFs into one document',
    category: 'pdf',
    subcategory: 'organize',
    icon: 'Combine',
    features: ['Unlimited files', 'Drag-drop reorder', 'Page preview', 'Fast processing', 'No file limit', 'Secure'],
    keywords: ['merge pdf', 'combine pdf', 'join pdf files', 'pdf merger online'],
    popular: true,
    trending: true,
  },
  {
    id: 'pdf-split',
    name: 'Split PDF',
    slug: 'split-pdf',
    description: 'Split PDF files by pages, ranges, or into individual pages. Extract specific pages or divide into equal parts.',
    shortDescription: 'Split PDFs by pages or ranges',
    category: 'pdf',
    subcategory: 'organize',
    icon: 'Scissors',
    features: ['Split by range', 'Split by pages', 'Extract pages', 'Split evenly', 'Custom ranges', 'Batch split'],
    keywords: ['split pdf', 'divide pdf', 'extract pdf pages', 'pdf splitter'],
    popular: true,
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    slug: 'pdf-to-jpg',
    description: 'Convert PDF pages to high-quality JPG images. Choose DPI, quality, and convert all pages or specific ones.',
    shortDescription: 'Convert PDF pages to JPG images',
    category: 'pdf',
    subcategory: 'conversion',
    icon: 'Image',
    features: ['High quality output', 'DPI control', 'Batch conversion', 'Specific pages', 'ZIP download', 'Quality settings'],
    keywords: ['pdf to jpg', 'pdf to image', 'convert pdf to jpg', 'pdf to jpeg'],
    popular: true,
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    slug: 'jpg-to-pdf',
    description: 'Convert JPG images to PDF documents. Combine multiple images into one PDF with custom page settings.',
    shortDescription: 'Convert JPG images to PDF document',
    category: 'pdf',
    subcategory: 'conversion',
    icon: 'FileImage',
    features: ['Multiple images', 'Page size options', 'Orientation control', 'Margin settings', 'Quality control', 'Reorder'],
    keywords: ['jpg to pdf', 'image to pdf', 'convert jpg to pdf', 'photo to pdf'],
    popular: true,
  },
  {
    id: 'pdf-rotate',
    name: 'Rotate PDF Pages',
    slug: 'rotate-pdf',
    description: 'Rotate PDF pages 90, 180, or 270 degrees. Rotate all pages or specific ones. Fix upside-down scans instantly.',
    shortDescription: 'Rotate PDF pages by any angle',
    category: 'pdf',
    subcategory: 'editing',
    icon: 'RotateCcw',
    features: ['Rotate 90/180/270', 'Specific pages', 'All pages', 'Preview', 'Batch processing'],
    keywords: ['rotate pdf', 'pdf rotation', 'fix pdf orientation'],
    popular: false,
  },
  {
    id: 'pdf-delete-pages',
    name: 'Delete PDF Pages',
    slug: 'delete-pdf-pages',
    description: 'Remove unwanted pages from PDF documents. Preview pages and select which ones to delete.',
    shortDescription: 'Remove pages from PDF documents',
    category: 'pdf',
    subcategory: 'editing',
    icon: 'Trash2',
    features: ['Page preview', 'Multi-select', 'Confirm deletion', 'Fast processing', 'Download result'],
    keywords: ['delete pdf pages', 'remove pdf pages', 'pdf page remover'],
    popular: false,
  },
  {
    id: 'pdf-watermark',
    name: 'PDF Watermark',
    slug: 'add-pdf-watermark',
    description: 'Add text or image watermarks to PDF documents. Customize font, size, position, opacity, and color.',
    shortDescription: 'Add watermarks to PDF documents',
    category: 'pdf',
    subcategory: 'editing',
    icon: 'Stamp',
    features: ['Text watermark', 'Image watermark', 'Custom position', 'Opacity control', 'Font settings', 'All pages'],
    keywords: ['pdf watermark', 'add watermark to pdf', 'pdf stamp'],
    popular: true,
  },
  {
    id: 'pdf-extract',
    name: 'Extract PDF Pages',
    slug: 'extract-pdf-pages',
    description: 'Extract specific pages from a PDF into a new document. Select individual pages or ranges to extract.',
    shortDescription: 'Extract specific pages from PDFs',
    category: 'pdf',
    subcategory: 'organize',
    icon: 'FileOutput',
    features: ['Page selection', 'Range extraction', 'Preview pages', 'Fast processing', 'New PDF output'],
    keywords: ['extract pdf pages', 'pdf page extractor', 'get pages from pdf'],
    popular: false,
  },
  {
    id: 'pdf-protect',
    name: 'Protect PDF',
    slug: 'protect-pdf',
    description: 'Add password protection to PDF files. Set permissions for printing, copying, and editing.',
    shortDescription: 'Password protect PDF files',
    category: 'pdf',
    subcategory: 'security',
    icon: 'Lock',
    features: ['Password protection', 'Permission settings', 'Encryption levels', 'Batch protection', 'Secure processing'],
    keywords: ['protect pdf', 'password pdf', 'encrypt pdf', 'secure pdf'],
    popular: true,
  },
  {
    id: 'pdf-unlock',
    name: 'Unlock PDF',
    slug: 'unlock-pdf',
    description: 'Remove password protection from PDF files. Unlock PDFs for editing, printing, and copying.',
    shortDescription: 'Remove PDF password protection',
    category: 'pdf',
    subcategory: 'security',
    icon: 'Unlock',
    features: ['Remove password', 'Unlock editing', 'Unlock printing', 'Batch unlock', 'Fast processing'],
    keywords: ['unlock pdf', 'remove pdf password', 'pdf unlocker'],
    popular: true,
  },
  {
    id: 'pdf-page-numbers',
    name: 'Add Page Numbers',
    slug: 'add-pdf-page-numbers',
    description: 'Add page numbers to PDF documents. Customize position, format, font, and starting number.',
    shortDescription: 'Add page numbers to PDFs',
    category: 'pdf',
    subcategory: 'editing',
    icon: 'Hash',
    features: ['Custom position', 'Number format', 'Font settings', 'Start number', 'Skip pages', 'Preview'],
    keywords: ['add page numbers pdf', 'pdf page numbering', 'number pdf pages'],
    popular: false,
  },
];

export const ALL_TOOLS = [...IMAGE_TOOLS, ...PDF_TOOLS];

export const TOOL_CATEGORIES = [
  { id: 'image-compression', name: 'Image Compression', slug: 'image-compression', icon: 'Minimize2', count: IMAGE_TOOLS.filter(t => t.subcategory === 'compression').length },
  { id: 'image-resize', name: 'Image Resize', slug: 'image-resize', icon: 'Maximize2', count: IMAGE_TOOLS.filter(t => t.subcategory === 'resize').length },
  { id: 'image-conversion', name: 'Image Conversion', slug: 'image-conversion', icon: 'RefreshCw', count: IMAGE_TOOLS.filter(t => t.subcategory === 'conversion').length },
  { id: 'image-editing', name: 'Image Editing', slug: 'image-editing', icon: 'Edit', count: IMAGE_TOOLS.filter(t => t.subcategory === 'editing').length },
  { id: 'image-filters', name: 'Image Filters', slug: 'image-filters', icon: 'Sparkles', count: IMAGE_TOOLS.filter(t => t.subcategory === 'filters').length },
  { id: 'pdf-compression', name: 'PDF Compression', slug: 'pdf-compression', icon: 'FileDown', count: PDF_TOOLS.filter(t => t.subcategory === 'compression').length },
  { id: 'pdf-organize', name: 'PDF Organization', slug: 'pdf-organize', icon: 'FolderOpen', count: PDF_TOOLS.filter(t => t.subcategory === 'organize').length },
  { id: 'pdf-conversion', name: 'PDF Conversion', slug: 'pdf-conversion', icon: 'FileSymlink', count: PDF_TOOLS.filter(t => t.subcategory === 'conversion').length },
  { id: 'pdf-editing', name: 'PDF Editing', slug: 'pdf-editing', icon: 'FileEdit', count: PDF_TOOLS.filter(t => t.subcategory === 'editing').length },
  { id: 'pdf-security', name: 'PDF Security', slug: 'pdf-security', icon: 'Shield', count: PDF_TOOLS.filter(t => t.subcategory === 'security').length },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return ALL_TOOLS.find(t => t.slug === slug);
}

export function getRelatedTools(tool: Tool, limit = 6): Tool[] {
  return ALL_TOOLS
    .filter(t => t.id !== tool.id && (t.category === tool.category || t.subcategory === tool.subcategory))
    .slice(0, limit);
}

export function getPopularTools(limit = 12): Tool[] {
  return ALL_TOOLS.filter(t => t.popular).slice(0, limit);
}

export function getTrendingTools(limit = 6): Tool[] {
  return ALL_TOOLS.filter(t => t.trending).slice(0, limit);
}
